# Generated by Django 4.2.6 on 2025-02-06 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_task_schudele_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='schudele_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 13, 21, 56, 4, 863172)),
        ),
    ]
