# Generated by Django 4.2.6 on 2025-02-06 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_contact_alter_task_schudele_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='schudele_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 13, 21, 56, 15, 705307)),
        ),
    ]
