# Generated by Django 4.2.6 on 2025-03-01 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_task_schudele_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='schudele_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 7, 30, 12, 655535)),
        ),
    ]
