# Generated by Django 4.2.6 on 2025-03-01 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_task_schudele_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='jus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('price', models.IntegerField()),
                ('ingredient', models.TextField()),
                ('diabetic', models.BooleanField()),
                ('due_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'jus',
                'verbose_name_plural': 'jus',
                'db_table': 'jus',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='schudele_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 7, 54, 2, 302118)),
        ),
    ]
