# Generated by Django 4.2.6 on 2025-03-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_task_schudele_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
