# Generated by Django 4.2.6 on 2025-03-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_delete_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
        migrations.AlterModelTable(
            name='jus',
            table=None,
        ),
    ]
