# Generated by Django 4.2.6 on 2025-03-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_contact_options_alter_contact_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='jus',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
