# Generated by Django 4.2.6 on 2025-03-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_contact_name_alter_jus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nom'),
        ),
    ]
