# Generated by Django 4.2.6 on 2025-03-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jus',
            old_name='due_date',
            new_name='date',
        ),
    ]
